'use server'

import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { parseCsv } from '@/lib/import/csv'
import { patientSchema } from '@/lib/validation/patient'
import { requirePermission } from '@/lib/auth'

const supported:Record<string,string>={nome:'name',name:'name',nome_social:'social_name',social_name:'social_name',nascimento:'birth_date',birth_date:'birth_date',cpf:'cpf',telefone:'phone',phone:'phone',whatsapp:'whatsapp',email:'email',objetivo:'objective',objective:'objective',status:'status'}

export async function importPatientsCsv(formData:FormData){const {supabase,organizationId}=await requirePermission('patient.write');const file=formData.get('file');if(!(file instanceof File)||!file.size)redirect('/app/importar?error='+encodeURIComponent('Selecione um arquivo CSV.'));if(file.size>2*1024*1024)redirect('/app/importar?error='+encodeURIComponent('O CSV deve ter no máximo 2 MB.'));const head=new Uint8Array(await file.slice(0,4).arrayBuffer());if(head[0]===0x4d&&head[1]===0x5a||head[0]===0x50&&head[1]===0x4b)redirect('/app/importar?error='+encodeURIComponent('O conteúdo não corresponde a um CSV de texto.'));let parsed;try{parsed=parseCsv((await file.text()).replace(/^\uFEFF/,''))}catch{redirect('/app/importar?error='+encodeURIComponent('CSV inválido. Verifique cabeçalhos, aspas e número de colunas.'))}const mapped=parsed.headers.map(header=>supported[header.trim().toLowerCase()]??null);if(!mapped.includes('name'))redirect('/app/importar?error='+encodeURIComponent('Inclua uma coluna nome ou name.'));const rows=parsed.rows.map((cells,index)=>{const raw_data=Object.fromEntries(parsed.headers.map((header,column)=>[header,cells[column]??'']));const candidate:Record<string,string>=Object.fromEntries(mapped.map((field,column)=>field?[field,cells[column]??'']:null).filter(Boolean) as [string,string][]);candidate.status=candidate.status||'ativo';const result=patientSchema.safeParse(candidate);return {row_number:index+2,raw_data,normalized_data:result.success?result.data:candidate,validation_errors:result.success?[]:result.error.issues.map(issue=>`${issue.path.join('.')}: ${issue.message}`)}});const {error}=await supabase.rpc('import_patients',{p_organization_id:organizationId,p_file_name:file.name,p_rows:rows});if(error)redirect('/app/importar?error='+encodeURIComponent(error.code==='23505'?'A importação contém CPF já cadastrado. Nenhum registro foi inserido.':'A importação falhou e foi revertida integralmente.'));revalidatePath('/app/importar');revalidatePath('/app/pacientes');redirect('/app/importar?message='+encodeURIComponent('Importação concluída. Consulte abaixo as linhas válidas e inválidas.'))}
