import { createFood } from '@/app/app/module-actions'
import { EmptyPanel, Feedback, PageHeader } from '@/components/module-ui'
import { requirePermission } from '@/lib/auth'

export default async function FoodsPage({ searchParams }: { searchParams: Promise<{ q?: string; message?: string; error?: string }> }) {
  const sp = await searchParams
  const { supabase, organizationId } = await requirePermission('clinical.read')
  let query = supabase.from('foods').select('*').or(`organization_id.is.null,organization_id.eq.${organizationId}`).order('name').limit(100)
  if (sp.q) query = query.ilike('name', `%${sp.q.replaceAll('%', '')}%`)
  const { data: foods } = await query
  return <div className="mx-auto max-w-7xl pb-20"><PageHeader eyebrow="Biblioteca clínica" title="Alimentos" description="Composição por porção e fonte. Nutrientes ausentes continuam ausentes e nunca são convertidos em zero."/><Feedback message={sp.message} error={sp.error}/><form className="np-card mt-6 flex gap-3 p-4"><input className="np-input" name="q" defaultValue={sp.q} placeholder="Buscar alimento"/><button className="np-button np-button-secondary">Buscar</button></form><div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><section>{foods?.length ? <div className="np-card overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-[#f7faf8] text-xs uppercase text-[#607269]"><tr><th className="p-4">Alimento</th><th className="p-4">Porção</th><th className="p-4">kcal</th><th className="p-4">P / C / G</th><th className="p-4">Fonte</th></tr></thead><tbody>{foods.map((food) => <tr className="border-t border-[#edf2ef]" key={food.id}><td className="p-4 font-bold">{food.name}</td><td className="p-4">{food.serving_quantity ?? '—'} {food.serving_unit ?? ''}</td><td className="p-4">{food.kcal ?? 'ausente'}</td><td className="p-4">{food.protein_g ?? '—'} / {food.carbs_g ?? '—'} / {food.fat_g ?? '—'} g</td><td className="p-4">{food.source ?? (food.organization_id ? 'Personalizado' : 'Não informada')}</td></tr>)}</tbody></table></div> : <EmptyPanel>Nenhum alimento corresponde à busca.</EmptyPanel>}</section><aside className="np-card p-5"><h2 className="font-bold">Alimento personalizado</h2><form action={createFood} className="mt-4 grid gap-3"><Input name="name" label="Nome" required/><div className="grid grid-cols-2 gap-3"><Input name="category" label="Categoria"/><Input name="source" label="Fonte"/></div><Input name="serving_description" label="Descrição da porção"/><div className="grid grid-cols-3 gap-3"><Input name="serving_quantity" label="Quantidade" type="number"/><Input name="serving_unit" label="Unidade"/><Input name="gram_weight" label="Peso (g)" type="number"/></div><div className="grid grid-cols-2 gap-3"><Input name="kcal" label="kcal" type="number"/><Input name="protein_g" label="Proteína (g)" type="number"/><Input name="carbs_g" label="Carboidrato (g)" type="number"/><Input name="fat_g" label="Gordura (g)" type="number"/><Input name="fiber_g" label="Fibra (g)" type="number"/><Input name="sodium_mg" label="Sódio (mg)" type="number"/></div><Input name="source_url" label="URL da fonte" type="url"/><button className="np-button">Salvar alimento</button></form></aside></div></div>
}

function Input({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label><span className="np-label">{label}</span><input className="np-input" step="any" {...props}/></label> }
