import { archiveGuidance, assignGuidance, createGuidance, updateGuidance } from '@/app/app/module-actions'
import { EmptyPanel, Feedback, PageHeader } from '@/components/module-ui'
import { requirePermission } from '@/lib/auth'

export default async function GuidancePage({ searchParams }: { searchParams: Promise<{ message?: string; error?: string }> }) {
  const sp = await searchParams
  const { supabase, organizationId } = await requirePermission('clinical.read')
  const [{ data: guidance }, { data: patients }, { data: plans }] = await Promise.all([
    supabase.from('guidance_library').select('*').eq('organization_id', organizationId).is('deleted_at', null).order('created_at', { ascending: false }),
    supabase.from('patients').select('id,name,social_name').eq('organization_id', organizationId).is('deleted_at', null).order('name'),
    supabase.from('nutrition_plans').select('id,title,patient_id').eq('organization_id', organizationId).is('deleted_at', null).order('created_at', { ascending: false }),
  ])
  return <div className="mx-auto max-w-7xl pb-20"><PageHeader eyebrow="Conduta" title="Orientações" description="Biblioteca clínica e liberação explícita para o paciente."/><Feedback {...sp}/><div className="mt-7 grid gap-5 xl:grid-cols-[1fr_.72fr]"><section className="grid content-start gap-4">{guidance?.length ? guidance.map((item) => <article className="np-card p-5" key={item.id}><div className="flex justify-between gap-3"><h2 className="font-bold">{item.title}</h2><span className="np-badge">{item.category ?? 'Geral'}</span></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6">{item.content}</p><details className="mt-4 border-t border-[#edf2ef] pt-4"><summary className="cursor-pointer text-sm font-bold text-[#167451]">Editar orientação</summary><form action={updateGuidance.bind(null,item.id)} className="mt-4 grid gap-3"><Input label="Título" name="title" defaultValue={item.title} required/><Input label="Categoria" name="category" defaultValue={item.category??''}/><label><span className="np-label">Conteúdo</span><textarea className="np-input" name="content" rows={8} defaultValue={item.content} required/></label><div className="flex gap-3"><button className="np-button">Salvar alterações</button><button className="text-sm font-bold text-red-700" formAction={archiveGuidance.bind(null,item.id)}>Arquivar</button></div></form></details></article>) : <EmptyPanel>Crie a primeira orientação reutilizável.</EmptyPanel>}</section><aside className="grid content-start gap-5"><section className="np-card p-5"><h2 className="font-bold">Nova orientação</h2><form action={createGuidance} className="mt-4 grid gap-3"><Input label="Título" name="title" required/><Input label="Categoria" name="category"/><label><span className="np-label">Conteúdo</span><textarea className="np-input" name="content" rows={8} required/></label><button className="np-button">Salvar na biblioteca</button></form></section><section className="np-card p-5"><h2 className="font-bold">Vincular ao paciente</h2><form action={assignGuidance} className="mt-4 grid gap-3"><Select label="Orientação" name="guidance_id" required items={(guidance ?? []).map((item) => [item.id,item.title])}/><Select label="Paciente" name="patient_id" required items={(patients ?? []).map((patient) => [patient.id,patient.social_name || patient.name])}/><Select label="Plano (opcional)" name="nutrition_plan_id" items={(plans ?? []).map((plan) => [plan.id,plan.title])}/><label className="flex gap-2 text-sm"><input type="checkbox" name="released_to_patient"/>Liberar no portal do paciente</label><button className="np-button">Vincular orientação</button></form></section></aside></div></div>
}
function Input({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label><span className="np-label">{label}</span><input className="np-input" {...props}/></label> }
function Select({ label, items, ...props }: React.SelectHTMLAttributes<HTMLSelectElement> & { label: string; items: [string,string][] }) { return <label><span className="np-label">{label}</span><select className="np-input" {...props}><option value="">Selecione</option>{items.map(([value,text]) => <option key={value} value={value}>{text}</option>)}</select></label> }
