import Link from 'next/link'
import { issueDocument, setDocumentRelease } from './actions'
import { EmptyPanel, Feedback, PageHeader } from '@/components/module-ui'
import { requirePermission } from '@/lib/auth'

export default async function DocumentsPage({ searchParams }: { searchParams: Promise<{ message?: string; error?: string; patient?: string }> }) {
  const sp = await searchParams
  const { supabase, organizationId } = await requirePermission('documents.read')
  const [{ data: documents }, { data: releases }, { data: patients }] = await Promise.all([
    supabase.from('documents').select('*').eq('organization_id', organizationId).order('issued_at', { ascending: false }).limit(100),
    supabase.from('document_releases').select('*').eq('organization_id', organizationId).is('revoked_at', null),
    supabase.from('patients').select('id,name,social_name').eq('organization_id', organizationId).is('deleted_at', null).order('name'),
  ])
  const names = new Map((patients ?? []).map((patient) => [patient.id,patient.social_name || patient.name]))
  const releasedIds = new Set((releases ?? []).map((release) => release.document_id))
  return <div className="mx-auto max-w-7xl pb-20"><PageHeader eyebrow="Emissão" title="Documentos" description="PDFs imutáveis em storage privado, identificados por checksum e liberados ao portal de forma explícita e revogável."/><Feedback {...sp}/><div className="mt-7 grid gap-5 xl:grid-cols-[1fr_390px]"><section>{documents?.length ? <div className="grid gap-3">{documents.map((document) => { const isReleased = releasedIds.has(document.id); return <article className="np-card p-5" key={document.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="font-bold">{document.title}</h2><span className="np-badge">{document.type}</span></div><p className="mt-2 text-sm text-[#607269]">{document.patient_id ? names.get(document.patient_id) : 'Sem paciente'} · nº {document.document_number} · {new Date(document.issued_at).toLocaleString('pt-BR')}</p><p className="mt-2 font-mono text-[10px] text-[#718179]">SHA-256 {document.checksum}</p></div><div className="flex flex-wrap gap-3"><Link className="np-button np-button-secondary" href={`/app/documentos/${document.id}/download`}>Baixar PDF</Link>{document.patient_id && <form action={setDocumentRelease.bind(null,document.id,document.patient_id,!isReleased)}><button className="np-button">{isReleased ? 'Revogar portal' : 'Liberar no portal'}</button></form>}</div></div></article> })}</div> : <EmptyPanel>Nenhum documento emitido.</EmptyPanel>}</section><aside className="np-card h-fit p-5"><h2 className="font-bold">Emitir PDF</h2><p className="mt-2 text-xs leading-5 text-[#607269]">A emissão é definitiva. Para corrigir conteúdo, emita um novo documento.</p><form action={issueDocument} className="mt-4 grid gap-3"><label><span className="np-label">Paciente</span><select className="np-input" name="patient_id" defaultValue={sp.patient ?? ''} required><option value="">Selecione</option>{patients?.map((patient) => <option value={patient.id} key={patient.id}>{patient.social_name || patient.name}</option>)}</select></label><label><span className="np-label">Tipo</span><select className="np-input" name="type"><option value="orientacao">Orientação</option><option value="plano_alimentar">Plano alimentar</option><option value="relatorio">Relatório</option><option value="declaracao">Declaração</option><option value="outro">Outro</option></select></label><label><span className="np-label">Título</span><input className="np-input" name="title" required/></label><label><span className="np-label">Conteúdo</span><textarea className="np-input" name="content" rows={12} required/></label><label className="flex gap-2 text-sm"><input type="checkbox" name="release_to_patient"/>Liberar no portal após emitir</label><button className="np-button">Gerar e armazenar PDF</button></form></aside></div></div>
}
