import { createCrmLead } from '@/app/app/module-actions'
import { EmptyPanel, Feedback, PageHeader } from '@/components/module-ui'
import { requirePermission } from '@/lib/auth'

const stages = [['new','Novo'],['contacted','Contatado'],['scheduled','Agendado'],['converted','Convertido'],['lost','Perdido']] as const
export default async function CrmPage({ searchParams }: { searchParams: Promise<{ message?: string; error?: string }> }) {
  const sp = await searchParams
  const { supabase, organizationId } = await requirePermission('patient.read')
  const { data: leads } = await supabase.from('crm_leads').select('*').eq('organization_id', organizationId).is('deleted_at', null).order('next_contact_at').order('created_at', { ascending: false })
  return <div className="mx-auto max-w-7xl pb-20"><PageHeader eyebrow="Relacionamento" title="CRM" description="Funil de captação com próxima ação e conversão vinculada ao cadastro real do paciente."/><Feedback {...sp}/><div className="mt-7 grid gap-5 xl:grid-cols-[1fr_360px]"><section>{leads?.length ? <div className="grid gap-4 md:grid-cols-2">{leads.map((lead) => <article className="np-card p-5" key={lead.id}><div className="flex justify-between gap-3"><div><h2 className="font-bold">{lead.name}</h2><p className="mt-1 text-sm text-[#607269]">{lead.phone || lead.email || 'Contato não informado'}</p></div><span className="np-badge">{stages.find(([value]) => value === lead.stage)?.[1] ?? lead.stage}</span></div>{lead.interest && <p className="mt-4 text-sm"><strong>Interesse:</strong> {lead.interest}</p>}{lead.next_contact_at && <p className="mt-2 text-xs text-[#607269]">Próximo contato: {new Date(lead.next_contact_at).toLocaleString('pt-BR')}</p>}{lead.notes && <p className="mt-3 whitespace-pre-wrap rounded-xl bg-[#f7faf8] p-3 text-sm">{lead.notes}</p>}</article>)}</div> : <EmptyPanel>Nenhum lead registrado.</EmptyPanel>}</section><aside className="np-card h-fit p-5"><h2 className="font-bold">Novo lead</h2><form action={createCrmLead} className="mt-4 grid gap-3"><Input label="Nome" name="name" required/><div className="grid grid-cols-2 gap-3"><Input label="Telefone" name="phone"/><Input label="E-mail" name="email" type="email"/></div><Input label="Origem" name="source" placeholder="Indicação, Instagram..."/><Input label="Interesse" name="interest"/><label><span className="np-label">Etapa</span><select className="np-input" name="stage">{stages.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><Input label="Próximo contato" name="next_contact_at" type="datetime-local"/><label><span className="np-label">Observações</span><textarea className="np-input" name="notes" rows={4}/></label><button className="np-button">Salvar lead</button></form></aside></div></div>
}
function Input({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label><span className="np-label">{label}</span><input className="np-input" {...props}/></label> }
