'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { z } from 'zod'
import { requireSuperadmin } from '@/lib/auth'

const go=(key:'message'|'error',message:string):never=>redirect(`/admin?${key}=${encodeURIComponent(message)}`)
export async function savePlan(planId:string,formData:FormData){const {supabase,user}=await requireSuperadmin();const reason=z.string().trim().min(5).max(500).parse(formData.get('reason'));const price=formData.get('price_reais')?Math.round(z.coerce.number().min(0).parse(formData.get('price_reais'))*100):null;const {error}=await supabase.from('saas_plans').update({name:z.string().trim().min(2).max(80).parse(formData.get('name')),price_cents:price,billing_interval:formData.get('billing_interval')||null,active:formData.get('active')==='on'}).eq('id',planId);if(error)go('error','Não foi possível atualizar o plano.');await supabase.from('admin_account_events').insert({actor_user_id:user.id,action:'saas.plan_updated',reason,metadata:{plan_id:planId}});revalidatePath('/admin');go('message','Plano atualizado e evento administrativo registrado.')}
export async function setSubscription(organizationId:string,formData:FormData){const {supabase,user}=await requireSuperadmin();const reason=z.string().trim().min(5).max(500).parse(formData.get('reason'));const planId=z.string().uuid().parse(formData.get('plan_id'));const status=z.enum(['trialing','active','past_due','cancelled','suspended']).parse(formData.get('status'));const {error}=await supabase.from('organization_subscriptions').upsert({organization_id:organizationId,plan_id:planId,status,provider:'manual',updated_at:new Date().toISOString()},{onConflict:'organization_id'});if(error)go('error','Não foi possível atualizar a assinatura.');await supabase.from('admin_account_events').insert({organization_id:organizationId,actor_user_id:user.id,action:`subscription.${status}`,reason,metadata:{plan_id:planId}});revalidatePath('/admin');go('message','Assinatura atualizada com trilha administrativa.')}
export async function setFeatureFlag(organizationId:string,flagId:string,enabled:boolean,formData:FormData){const {supabase,user}=await requireSuperadmin();const reason=z.string().trim().min(5).max(500).parse(formData.get('reason'));const {error}=await supabase.from('organization_feature_flags').upsert({organization_id:organizationId,feature_flag_id:flagId,enabled,updated_by:user.id},{onConflict:'organization_id,feature_flag_id'});if(error)go('error','Não foi possível alterar a feature flag.');await supabase.from('admin_account_events').insert({organization_id:organizationId,actor_user_id:user.id,action:'feature_flag.updated',reason,metadata:{flag_id:flagId,enabled}});revalidatePath('/admin');go('message','Feature flag atualizada com justificativa registrada.')}
