'use client'

import { useActionState, useMemo, useState } from 'react'
import { createCalendarEntry, createServiceType, rescheduleAppointment, savePublicBookingProfile, type AgendaActionState } from '@/app/app/agenda/actions'

const initial: AgendaActionState = { ok: false, message: '' }
type Service = { id: string; name: string; duration_minutes: number; modality: string }
type Patient = { id: string; name: string; social_name: string | null }
type Professional = { user_id: string; label: string }

function iso(local: string) { return local ? new Date(local).toISOString() : '' }

export function CalendarEntryForm({ services, patients, professionals }: { services: Service[]; patients: Patient[]; professionals: Professional[] }) {
  const [state, action, pending] = useActionState(createCalendarEntry, initial)
  const [entryType, setEntryType] = useState('appointment')
  const [start, setStart] = useState('')
  const [end, setEnd] = useState('')
  const [serviceId, setServiceId] = useState(services[0]?.id ?? '')
  const service = useMemo(() => services.find((item) => item.id === serviceId), [serviceId, services])
  const derivedEnd = entryType === 'appointment' && start && service ? new Date(new Date(start).getTime() + service.duration_minutes * 60_000).toISOString() : iso(end)
  return <form action={action} className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><label><span className="np-label">Tipo de entrada</span><select className="np-input" name="entry_type" value={entryType} onChange={(event) => setEntryType(event.target.value)}><option value="appointment">Consulta</option><option value="block">Bloqueio</option><option value="vacation">Férias</option><option value="lunch">Almoço</option><option value="personal">Compromisso</option><option value="unavailable">Indisponibilidade</option></select></label><label><span className="np-label">Profissional</span><select className="np-input" name="professional_user_id" required>{professionals.map((item) => <option value={item.user_id} key={item.user_id}>{item.label}</option>)}</select></label></div>{entryType === 'appointment' ? <div className="grid gap-4 sm:grid-cols-2"><label><span className="np-label">Paciente</span><select className="np-input" name="patient_id" required><option value="">Selecione</option>{patients.map((patient) => <option value={patient.id} key={patient.id}>{patient.social_name || patient.name}</option>)}</select></label><label><span className="np-label">Tipo de consulta</span><select className="np-input" name="service_type_id" value={serviceId} onChange={(event) => setServiceId(event.target.value)} required>{services.map((item) => <option value={item.id} key={item.id}>{item.name} · {item.duration_minutes} min</option>)}</select></label></div> : <label><span className="np-label">Título do bloqueio</span><input className="np-input" name="title" defaultValue="Indisponível" required /></label>}<div className="grid gap-4 sm:grid-cols-2"><label><span className="np-label">Início</span><input className="np-input" type="datetime-local" value={start} onChange={(event) => setStart(event.target.value)} required /></label>{entryType !== 'appointment' && <label><span className="np-label">Término</span><input className="np-input" type="datetime-local" value={end} onChange={(event) => setEnd(event.target.value)} required /></label>}</div><input type="hidden" name="starts_at" value={iso(start)} /><input type="hidden" name="ends_at" value={derivedEnd} /><input type="hidden" name="modality" value={service?.modality === 'online' ? 'online' : 'presencial'} /><label><span className="np-label">Observações</span><textarea className="np-input min-h-20" name="notes" /></label>{state.message && <p role="status" className={state.ok ? 'text-sm text-emerald-700' : 'text-sm text-red-700'}>{state.message}</p>}<button className="np-button" disabled={pending || !start || !derivedEnd}>{pending ? 'Salvando…' : entryType === 'appointment' ? 'Agendar consulta' : 'Criar bloqueio'}</button></form>
}

export function ServiceTypeForm() {
  const [state, action, pending] = useActionState(createServiceType, initial)
  return <form action={action} className="grid gap-3"><div className="grid gap-3 sm:grid-cols-2"><label><span className="np-label">Nome</span><input className="np-input" name="name" required /></label><label><span className="np-label">Categoria</span><select className="np-input" name="kind"><option value="first_visit">Primeira consulta</option><option value="return">Retorno</option><option value="follow_up">Acompanhamento</option><option value="custom">Personalizado</option></select></label><label><span className="np-label">Duração (min)</span><input className="np-input" name="duration_minutes" type="number" min="10" max="480" defaultValue="60" required /></label><label><span className="np-label">Preço (R$)</span><input className="np-input" name="price_reais" type="number" min="0" step="0.01" defaultValue="0" required /></label><label><span className="np-label">Modalidade</span><select className="np-input" name="modality"><option value="hibrido">Híbrido</option><option value="presencial">Presencial</option><option value="online">Online</option></select></label><label><span className="np-label">Cor</span><input className="np-input h-11" name="color" type="color" defaultValue="#167451" /></label></div><label><span className="np-label">Instruções</span><textarea className="np-input min-h-20" name="instructions" /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="public_enabled" />Disponibilizar no agendamento público</label>{state.message && <p role="status" className={state.ok ? 'text-sm text-emerald-700' : 'text-sm text-red-700'}>{state.message}</p>}<button className="np-button np-button-secondary" disabled={pending}>{pending ? 'Salvando…' : 'Salvar tipo de consulta'}</button></form>
}

export function RescheduleForm({ id }: { id: string }) {
  const [state, action, pending] = useActionState(rescheduleAppointment, initial)
  const [local, setLocal] = useState('')
  return <form action={action} className="mt-3 flex flex-wrap items-end gap-2"><input type="hidden" name="id" value={id} /><input type="hidden" name="starts_at" value={iso(local)} /><label><span className="np-label">Novo início</span><input className="np-input" type="datetime-local" value={local} onChange={(event) => setLocal(event.target.value)} required /></label><button className="np-button np-button-secondary" disabled={pending || !local}>Reagendar</button>{state.message && <span className={state.ok ? 'text-xs text-emerald-700' : 'text-xs text-red-700'}>{state.message}</span>}</form>
}

export function PublicBookingProfileForm({ initialProfile, defaultName, clinicName, timezone }: { initialProfile?: Record<string, unknown> | null; defaultName: string; clinicName: string; timezone: string }) {
  const [state, action, pending] = useActionState(savePublicBookingProfile, initial)
  return <form action={action} className="grid gap-3"><div className="grid gap-3 sm:grid-cols-2"><label><span className="np-label">Endereço público</span><div className="flex items-center rounded-xl border border-[#cfddd5] bg-white px-3"><span className="text-xs text-[#607269]">/agenda/</span><input className="w-full border-0 py-3 outline-none" name="slug" defaultValue={String(initialProfile?.slug ?? '')} placeholder="dra-mariana" required /></div></label><label><span className="np-label">Nome exibido</span><input className="np-input" name="display_name" defaultValue={String(initialProfile?.display_name ?? defaultName)} required /></label><label><span className="np-label">Clínica</span><input className="np-input" name="clinic_name" defaultValue={String(initialProfile?.clinic_name ?? clinicName)} /></label><label><span className="np-label">Local público</span><input className="np-input" name="public_location" defaultValue={String(initialProfile?.public_location ?? '')} /></label></div><input type="hidden" name="timezone" value={timezone} /><label><span className="np-label">Apresentação pública</span><textarea className="np-input min-h-20" name="public_bio" defaultValue={String(initialProfile?.public_bio ?? '')} /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="enabled" defaultChecked={Boolean(initialProfile?.enabled)} />Ativar página pública</label>{state.message && <p role="status" className={state.ok ? 'text-sm text-emerald-700' : 'text-sm text-red-700'}>{state.message}</p>}<button className="np-button np-button-secondary" disabled={pending}>Salvar agendamento público</button></form>
}
