'use server'

import { createHash, randomBytes } from 'node:crypto'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { z } from 'zod'
import { requirePermission } from '@/lib/auth'

const go=(key:'message'|'error',value:string):never=>redirect(`/app/equipe?${key}=${encodeURIComponent(value)}`)
export async function createTeamInvitation(formData:FormData){const {supabase,organizationId,user}=await requirePermission('team.manage');const email=z.string().trim().toLowerCase().email().parse(formData.get('email'));const role=z.enum(['nutritionist','assistant']).parse(formData.get('role'));const token=randomBytes(32).toString('base64url');const tokenHash=createHash('sha256').update(token).digest('hex');const {error}=await supabase.from('team_invitations').insert({organization_id:organizationId,email,role,token_hash:tokenHash,invited_by:user.id,expires_at:new Date(Date.now()+7*86400000).toISOString()});if(error)go('error','Não foi possível criar o convite. Verifique se já existe um convite pendente para o e-mail.');const origin=process.env.NEXT_PUBLIC_APP_URL??'http://localhost:3000';revalidatePath('/app/equipe');redirect(`/app/equipe?message=${encodeURIComponent('Convite criado. Copie o link abaixo e envie pelo canal de sua escolha.')}&invite=${encodeURIComponent(`${origin}/convites/equipe/${token}`)}`)}
export async function revokeTeamInvitation(id:string){const {supabase,organizationId}=await requirePermission('team.manage');const {error}=await supabase.from('team_invitations').update({revoked_at:new Date().toISOString()}).eq('organization_id',organizationId).eq('id',id).is('accepted_at',null);if(error)go('error','Não foi possível revogar o convite.');revalidatePath('/app/equipe');go('message','Convite revogado.')}
export async function deactivateMember(userId:string){const {supabase,organizationId,user}=await requirePermission('team.manage');if(userId===user.id)go('error','Você não pode desativar o próprio acesso.');const {data:member}=await supabase.from('organization_members').select('role').eq('organization_id',organizationId).eq('user_id',userId).single();if(member?.role==='owner')go('error','O proprietário não pode ser desativado por esta tela.');const {error}=await supabase.from('organization_members').update({active:false}).eq('organization_id',organizationId).eq('user_id',userId);if(error)go('error','Não foi possível desativar o membro.');revalidatePath('/app/equipe');go('message','Acesso do membro desativado.')}
export async function changeMemberRole(userId:string,formData:FormData){const {supabase,organizationId,user}=await requirePermission('team.manage');if(userId===user.id)go('error','Você não pode alterar o próprio perfil.');const role=z.enum(['nutritionist','assistant']).parse(formData.get('role'));const {data:member}=await supabase.from('organization_members').select('role').eq('organization_id',organizationId).eq('user_id',userId).single();if(!member||member.role==='owner')go('error','O perfil do proprietário não pode ser alterado.');const {error}=await supabase.from('organization_members').update({role}).eq('organization_id',organizationId).eq('user_id',userId);if(error)go('error','Não foi possível alterar o perfil.');revalidatePath('/app/equipe');go('message','Perfil do membro atualizado e auditado.')}
export async function setPermissionOverride(memberUserId:string,permissionKey:string,allowed:boolean){const {supabase,organizationId,user}=await requirePermission('team.manage');const {error}=await supabase.from('member_permission_overrides').upsert({organization_id:organizationId,member_user_id:memberUserId,permission_key:permissionKey,allowed,granted_by:user.id},{onConflict:'organization_id,member_user_id,permission_key'});if(error)go('error','Não foi possível alterar a permissão.');revalidatePath('/app/equipe');go('message','Permissão específica atualizada.')}
