'use server'

import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { z } from 'zod'
import { requireOrganization, requirePermission } from '@/lib/auth'

const optional = (value: FormDataEntryValue | null) => String(value ?? '').trim() || null
const feedback = (key:'message'|'error',value:string):never => redirect(`/app/configuracoes?${key}=${encodeURIComponent(value)}`)

export async function saveProfessionalSettings(formData:FormData){const {supabase,organizationId,user}=await requireOrganization();const name=z.string().trim().min(2).max(160).parse(formData.get('professional_name'));const specialties=String(formData.get('specialties')??'').split(',').map(item=>item.trim()).filter(Boolean);const {error:profileError}=await supabase.from('profiles').update({professional_name:name,phone:optional(formData.get('phone'))}).eq('id',user.id);if(profileError)feedback('error','Não foi possível atualizar o perfil.');const {error}=await supabase.from('professional_settings').upsert({organization_id:organizationId,user_id:user.id,crn:optional(formData.get('crn')),crn_region:optional(formData.get('crn_region')),professional_document:optional(formData.get('professional_document')),specialties,service_mode:formData.get('service_mode')??'hibrido',default_duration_minutes:z.coerce.number().int().min(10).max(480).parse(formData.get('default_duration_minutes')),default_price_cents:formData.get('default_price_reais')?Math.round(z.coerce.number().min(0).parse(formData.get('default_price_reais'))*100):null,document_header:optional(formData.get('document_header')),document_footer:optional(formData.get('document_footer')),signature_enabled:false},{onConflict:'organization_id,user_id'});if(error)feedback('error','Não foi possível atualizar os dados profissionais.');revalidatePath('/app/configuracoes');feedback('message','Perfil profissional atualizado.')}

export async function saveOrganizationSettings(formData:FormData){const {supabase,organizationId}=await requirePermission('team.manage');const name=z.string().trim().min(2).max(160).parse(formData.get('name'));const timezone=z.string().trim().min(3).max(80).parse(formData.get('timezone'));const {error}=await supabase.from('organizations').update({name,timezone,locale:'pt-BR'}).eq('id',organizationId);if(error)feedback('error','Não foi possível atualizar a clínica.');const reminderHours=String(formData.get('appointment_reminder_hours')??'24').split(',').map(Number).filter(value=>Number.isInteger(value)&&value>0&&value<=720);const {error:settingsError}=await supabase.from('organization_settings').upsert({organization_id:organizationId,appointment_reminder_hours:reminderHours.length?reminderHours:[24],default_payment_due_days:z.coerce.number().int().min(0).max(365).parse(formData.get('default_payment_due_days')),retention_months:z.coerce.number().int().min(1).max(1200).parse(formData.get('retention_months'))},{onConflict:'organization_id'});if(settingsError)feedback('error','Clínica atualizada, mas as preferências não foram salvas.');revalidatePath('/app/configuracoes');feedback('message','Configurações da clínica atualizadas.')}

export async function saveBusinessHours(formData:FormData){const {supabase,organizationId,user}=await requirePermission('agenda.write');const weekdays=formData.getAll('weekday').map(Number).filter(value=>Number.isInteger(value)&&value>=0&&value<=6);const startsAt=z.string().regex(/^\d{2}:\d{2}$/).parse(formData.get('starts_at'));const endsAt=z.string().regex(/^\d{2}:\d{2}$/).parse(formData.get('ends_at'));if(endsAt<=startsAt)feedback('error','O fim do expediente deve ser posterior ao início.');const {error:deleteError}=await supabase.from('business_hours').delete().eq('organization_id',organizationId).eq('professional_user_id',user.id);if(deleteError)feedback('error','Não foi possível substituir os horários.');if(weekdays.length){const {error}=await supabase.from('business_hours').insert(weekdays.map(weekday=>({organization_id:organizationId,professional_user_id:user.id,weekday,starts_at:startsAt,ends_at:endsAt})));if(error)feedback('error','Não foi possível salvar os horários.')}revalidatePath('/app/configuracoes');feedback('message','Disponibilidade semanal atualizada.')}
